name: Node.js CI

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      shell: bash
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
      shell: bash
    - run: npm run build --if-present
      shell: bash
    - run: npm test
      shell: bash
